In [1]:
import os
import matplotlib.pyplot as plt
import pandas as pd
from ultralytics import YOLO
import torch
%matplotlib inline

### Get the best weight for each model

In [2]:
cwd = os.getcwd()
yolo_dirs = ['yolo8', 'yolo11', 'yolo9', 'yolo12']
gen_dir = [os.path.join(cwd, gen) for gen in yolo_dirs]
models_name = [os.listdir(model_dir) for model_dir in gen_dir if os.path.isdir(model_dir)]

model_dirs = []
for gen, models in zip(gen_dir, models_name):
    for model in models:
        path = os.path.join(gen, model)
        if os.path.isdir(path):
            model_dirs.append(path)
        
models_weight_path = [os.path.join(model_dir, "weights", "best.pt") for model_dir in model_dirs]
models_weight_path

['/home/kien/Desktop/projects/Amir_research/yolo/yolo8/yolov8m/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo8/yolov8n/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo8/yolov8l/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo8/yolov8x/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo8/yolov8s/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo11/yolo11l/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo11/yolo11n/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo11/yolo11s/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo11/yolo11m/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo11/yolo11x/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo9/yolov9e2/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo9/yolov9s/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo9/yolov9t/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo9/yolov9c/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo9/yolov9m/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo12/yolo12x/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo12/yolo12l/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo12/yolo12s/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo12/yolo12n/weights/best.pt',
 '/home/kien/Desktop/projects/Amir_research/yolo/yolo12/yolo12m/weights/best.pt']

### Load all yolo models into DF

In [3]:
from collections import defaultdict
dic = defaultdict(list)

for model_path in models_weight_path:
    
    str_split = model_path.split("/")
    dic["gen"].append(str_split[7])
    dic["name"].append(str_split[8])
    dic["model"].append(YOLO(model_path))

    
df = pd.DataFrame(dic)
df

       gen      name                                              model
0    yolo8   yolov8m  YOLO(\n  (model): DetectionModel(\n    (model)...
1    yolo8   yolov8n  YOLO(\n  (model): DetectionModel(\n    (model)...
2    yolo8   yolov8l  YOLO(\n  (model): DetectionModel(\n    (model)...
3    yolo8   yolov8x  YOLO(\n  (model): DetectionModel(\n    (model)...
4    yolo8   yolov8s  YOLO(\n  (model): DetectionModel(\n    (model)...
5   yolo11   yolo11l  YOLO(\n  (model): DetectionModel(\n    (model)...
6   yolo11   yolo11n  YOLO(\n  (model): DetectionModel(\n    (model)...
7   yolo11   yolo11s  YOLO(\n  (model): DetectionModel(\n    (model)...
8   yolo11   yolo11m  YOLO(\n  (model): DetectionModel(\n    (model)...
9   yolo11   yolo11x  YOLO(\n  (model): DetectionModel(\n    (model)...
10   yolo9  yolov9e2  YOLO(\n  (model): DetectionModel(\n    (model)...
11   yolo9   yolov9s  YOLO(\n  (model): DetectionModel(\n    (model)...
12   yolo9   yolov9t  YOLO(\n  (model): DetectionModel(\n    (model)...
13   yolo9   yolov9c  YOLO(\n  (model): DetectionModel(\n    (model)...
14   yolo9   yolov9m  YOLO(\n  (model): DetectionModel(\n    (model)...
15  yolo12   yolo12x  YOLO(\n  (model): DetectionModel(\n    (model)...
16  yolo12   yolo12l  YOLO(\n  (model): DetectionModel(\n    (model)...
17  yolo12   yolo12s  YOLO(\n  (model): DetectionModel(\n    (model)...
18  yolo12   yolo12n  YOLO(\n  (model): DetectionModel(\n    (model)...
19  yolo12   yolo12m  YOLO(\n  (model): DetectionModel(\n    (model)...

### EVAL

In [4]:
import os, gc, torch

results = []
data_dir = os.path.join("..","pretrain_models","data","mobile detection.v7i.yolov11","data.yaml")

VAL_KW = dict(
    data=data_dir,
    split="test",
    imgsz=640,
    iou=0.50,
    conf=0.001,
    batch=1,
    device=0,
    half=True,      
    workers=0,
    verbose=False,
)


with torch.no_grad():
    for i, yolo_obj in df["model"].items():
        try:
            # Make sure it's on GPU only while we need it
            yolo_obj.model.to("cuda").eval()

            res = yolo_obj.val(**VAL_KW)

            results.append(res)
        finally:
            # Move OFF GPU, break all refs, and clear caches
            try:
                yolo_obj.model.to("cpu")
            except Exception:
                pass
            df.at[i, "model"] = None    # <- break the DF reference
            del yolo_obj
            gc.collect()
            torch.cuda.synchronize()
            torch.cuda.empty_cache()

Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
Model summary (fused): 92 layers, 25,842,076 parameters, 0 gradients, 78.7 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1641.7±587.1 MB/s, size: 39.9 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 619.5Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 75.3it/s 3.6s0.1s
                   all        270        271      0.959      0.926      0.963      0.608
Speed: 0.3ms preprocess, 7.0ms inference, 0.0ms loss, 1.4ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
Model summary (fused): 72 layers, 3,006,428 parameters, 0 gradients, 8.1 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1699.8±428.8 MB/s, size: 40.6 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 595.1Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 90.2it/s 3.0s0.0s
                   all        270        271      0.956      0.928      0.957      0.599
Speed: 0.3ms preprocess, 5.5ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val2
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
Model summary (fused): 112 layers, 43,609,692 parameters, 0 gradients, 164.8 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3311.0±676.0 MB/s, size: 45.7 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 759.0Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 67.3it/s 4.0s0.1s
                   all        270        271      0.953      0.942      0.959      0.617
Speed: 0.2ms preprocess, 9.2ms inference, 0.0ms loss, 1.0ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val3
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
Model summary (fused): 112 layers, 68,127,420 parameters, 0 gradients, 257.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3259.5±718.1 MB/s, size: 42.8 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 742.1Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 47.2it/s 5.7s0.1s
                   all        270        271      0.962      0.949      0.968      0.626
Speed: 0.2ms preprocess, 15.7ms inference, 0.0ms loss, 1.1ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val4
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
Model summary (fused): 72 layers, 11,127,132 parameters, 0 gradients, 28.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3163.5±554.3 MB/s, size: 42.5 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 757.5Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 98.7it/s 2.7ss<0.0s
                   all        270        271       0.95      0.942      0.958      0.598
Speed: 0.2ms preprocess, 5.2ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val5
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLO11l summary (fused): 190 layers, 25,282,396 parameters, 0 gradients, 86.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2658.1±1007.3 MB/s, size: 40.4 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 961.3Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 42.8it/s 6.3s0.1s
                   all        270        271       0.95      0.936      0.962      0.618
Speed: 0.2ms preprocess, 18.4ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val6
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLO11n summary (fused): 100 layers, 2,582,932 parameters, 0 gradients, 6.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2984.8±505.3 MB/s, size: 39.1 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 1.0Mit/s 0.0s0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 57.3it/s 4.7s<0.0s
                   all        270        271      0.956      0.925      0.947      0.591
Speed: 0.2ms preprocess, 12.5ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val7
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLO11s summary (fused): 100 layers, 9,414,348 parameters, 0 gradients, 21.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3413.5±757.0 MB/s, size: 43.0 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 1.0Mit/s 0.0s0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 76.0it/s 3.6s0.0s
                   all        270        271      0.975      0.941      0.967      0.602
Speed: 0.2ms preprocess, 8.2ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val8
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLO11m summary (fused): 125 layers, 20,033,116 parameters, 0 gradients, 67.7 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3437.3±677.6 MB/s, size: 49.5 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 841.4Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 74.8it/s 3.6s<0.0s
                   all        270        271      0.973      0.946      0.967      0.612
Speed: 0.2ms preprocess, 8.5ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val9
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLO11x summary (fused): 190 layers, 56,831,644 parameters, 0 gradients, 194.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3057.7±620.0 MB/s, size: 39.6 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 764.7Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 40.8it/s 6.6s0.1s
                   all        270        271      0.916      0.931      0.939      0.593
Speed: 0.2ms preprocess, 19.1ms inference, 0.0ms loss, 1.0ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val10
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLOv9e summary (fused): 279 layers, 57,379,484 parameters, 0 gradients, 189.1 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3352.1±688.2 MB/s, size: 44.0 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 980.5Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 40.0it/s 6.7s0.1s
                   all        270        271      0.966      0.925      0.959      0.584
Speed: 0.2ms preprocess, 19.4ms inference, 0.0ms loss, 1.0ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val11
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLOv9s summary (fused): 197 layers, 7,168,636 parameters, 0 gradients, 26.7 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3063.6±919.6 MB/s, size: 41.6 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 861.2Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 52.9it/s 5.1s0.1s
                   all        270        271      0.963      0.931      0.959      0.627
Speed: 0.2ms preprocess, 13.8ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val12
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLOv9t summary (fused): 197 layers, 1,971,564 parameters, 0 gradients, 7.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2607.2±748.0 MB/s, size: 40.8 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 1.1Mit/s 0.0s0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 53.8it/s 5.0s0.0s
                   all        270        271      0.973      0.942      0.957      0.615
Speed: 0.2ms preprocess, 13.2ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val13
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLOv9c summary (fused): 156 layers, 25,322,332 parameters, 0 gradients, 102.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2719.5±695.4 MB/s, size: 41.2 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 769.9Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 62.9it/s 4.3s0.1s
                   all        270        271      0.962      0.943      0.968       0.63
Speed: 0.2ms preprocess, 10.8ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val14
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLOv9m summary (fused): 151 layers, 20,015,884 parameters, 0 gradients, 76.5 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2904.0±432.8 MB/s, size: 40.7 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 914.8Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 61.3it/s 4.4s0.1s
                   all        270        271      0.957      0.955      0.964      0.607
Speed: 0.2ms preprocess, 11.0ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val15
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLOv12x summary (fused): 283 layers, 59,047,964 parameters, 0 gradients, 198.5 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2842.5±1057.0 MB/s, size: 43.4 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 1.1Mit/s 0.0s0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 39.4it/s 6.9s0.1s
                   all        270        271      0.955      0.885      0.949      0.557
Speed: 0.2ms preprocess, 19.6ms inference, 0.0ms loss, 1.1ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val16
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLOv12l summary (fused): 283 layers, 26,342,156 parameters, 0 gradients, 88.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2956.2±670.3 MB/s, size: 42.1 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 818.3Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 40.1it/s 6.7s0.1s
                   all        270        271      0.953       0.93      0.957      0.608
Speed: 0.2ms preprocess, 19.3ms inference, 0.0ms loss, 1.1ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val17
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLOv12s summary (fused): 159 layers, 9,232,428 parameters, 0 gradients, 21.2 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1998.7±924.0 MB/s, size: 44.9 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 900.2Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 62.5it/s 4.3s0.0s
                   all        270        271      0.961      0.936      0.963      0.603
Speed: 0.2ms preprocess, 10.7ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val18
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLOv12n summary (fused): 159 layers, 2,557,508 parameters, 0 gradients, 6.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2573.1±704.8 MB/s, size: 38.3 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 917.7Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 61.6it/s 4.4s0.1s
                   all        270        271      0.951      0.916      0.938      0.589
Speed: 0.3ms preprocess, 10.5ms inference, 0.0ms loss, 1.0ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val19
Ultralytics 8.3.195 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 3080, 9864MiB)
YOLOv12m summary (fused): 169 layers, 20,107,996 parameters, 0 gradients, 67.1 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2968.2±503.0 MB/s, size: 44.5 KB)
val: Scanning /home/kien/Desktop/projects/Amir_research/pretrain_models/data/mobile detection.v7i.yolov11/test/labels.cache... 270 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 270/270 548.9Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 270/270 58.7it/s 4.6s0.1s
                   all        270        271      0.941       0.92      0.951      0.582
Speed: 0.2ms preprocess, 11.6ms inference, 0.0ms loss, 1.1ms postprocess per image
Results saved to /home/kien/Desktop/projects/Amir_research/yolo/runs/detect/val20

In [5]:
df = df.drop(columns=["model"])
df["map50_95"] = [result.box.map for result in results]
df["speed"] = [sum(result.speed.values()) for result in results]
df["s_per_pic"] = df.speed/270
df["fps"] = 1/df["s_per_pic"]

In [6]:
df

       gen      name  map50_95      speed  s_per_pic        fps
0    yolo8   yolov8m  0.607781   8.612888   0.031900  31.348368
1    yolo8   yolov8n  0.599128   6.662799   0.024677  40.523512
2    yolo8   yolov8l  0.616803  10.406087   0.038541  25.946353
3    yolo8   yolov8x  0.626444  16.938544   0.062735  15.939977
4    yolo8   yolov8s  0.598078   6.206764   0.022988  43.500931
5   yolo11   yolo11l  0.618033  19.420865   0.071929  13.902573
6   yolo11   yolo11n  0.590898  13.486247   0.049949  20.020395
7   yolo11   yolo11s  0.602350   9.198367   0.034068  29.353037
8   yolo11   yolo11m  0.612337   9.507070   0.035211  28.399918
9   yolo11   yolo11x  0.592882  20.327080   0.075285  13.282774
10   yolo9  yolov9e2  0.584236  20.637440   0.076435  13.083018
11   yolo9   yolov9s  0.627471  14.830410   0.054927  18.205835
12   yolo9   yolov9t  0.614804  14.331385   0.053079  18.839770
13   yolo9   yolov9c  0.629655  11.834809   0.043833  22.814057
14   yolo9   yolov9m  0.607106  12.144800   0.044981  22.231736
15  yolo12   yolo12x  0.556568  20.936207   0.077542  12.896319
16  yolo12   yolo12l  0.608390  20.560788   0.076151  13.131793
17  yolo12   yolo12s  0.603352  11.864524   0.043943  22.756917
18  yolo12   yolo12n  0.589377  11.780312   0.043631  22.919596
19  yolo12   yolo12m  0.582289  12.956818   0.047988  20.838449

In [7]:
df.to_csv("./runs/val_results.csv", index=False)